### PR TITLE
Fixed the size of Guest Cards.

### PR DESCRIPTION
**Pull request by geekofshire**
#41 Fixed the issue do alert me in case of any discrepancies and if pr is accepted do add hacktoberfest labels. Thank You!!
Screenshot from 2022-10-08 01-15-45

### CODE REVIEW

**Comment by SamarthTMSL** [comment]
@geekofshire Bring the card contents to the centre of the card and give a pull request

**Comment by geekofshire** [comment]
@SamarthTMSL sure

**Comment by geekofshire** [comment]
@SamarthTMSL do check the cards now.

**Comment by geekofshire** [comment]
@SamarthTMSL if there is any problem in my PR please alert me.

**Comment by SamarthTMSL** [comment]
Sure @geekofshire We will check and inform as soon as possible

**Review by SamarthTMSL — CHANGES_REQUESTED** [review]
These Changes are making the cards size fixed but isn't bringing the card content to the centre of the cards as asked

**Comment by geekofshire** [comment]
The card contents are in the center I fixed them in later commits. @SamarthTMSL 
Screenshot from 2022-10-09 14-53-38

**Comment by SamarthTMSL** [comment]
194748871-e1722d16-3d60-4c98-9262-1c4bff5be065

Suppose the yellow one is your card and We want the blue circle to be at the centre of the card but your code isn't doing that.
Kindly look into it @geekofshire

**Comment by geekofshire** [comment]
@SamarthTMSL thanks for the clarity. I am on it.

**Comment by geekofshire** [comment]
@SamarthTMSL do check.
Screenshot from 2022-10-09 21-46-42

**Review by SamarthTMSL — APPROVED** [review]

**Pull request merged**
